config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'
  resources :users, only: [:show]
  resources :services

  resources :services do
    resources :orders, only: [:create]
  end

  resources :orders, only: [:show]

  get '/user_orders' => 'orders#user_orders'

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :service

  validates :quantity, presence: true
  validates :price, presence: true
  validates :total_price, presence: true
  validates :service_id, presence: true

end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :user
  has_many :orders

  has_attached_file :image, styles: {medium: "300x300>", small: "230x140", thumb:"100x100>"}

  validates :title, presence: true, length: {maximum:80}
  validates :description, presence: true, length: {maximum:1200}
  validates :price, presence: true
  validates :delivery_time, presence: false
  validates :revisions, presence: false
  validates :requirements, presence: true, length: {maximum:450}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  default_scope -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :fullname, presence: true, length: {maximum: 50}
  validates :description, presence: false, length: {maximum: 1500}

  has_many :services
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname])
      devise_parameter_sanitizer.permit(:account_update, keys: [:fullname, :email, :password, :description])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_service, only: [:new, :create, :show, :edit, :update]

  def new
  	@order = @service.orders.new
  end

  def create
  	@order = current_user.orders.create(order_params)
  	@order.total_price = params[:order][:price].to_i * params[:order][:quantity].to_i
  	token = params[:stripeToken]
  	puts "hello"
  	puts token
    charge = Stripe::Charge.create source: params[:stripeToken],
                          amount: @order.total_price * 100,
                          description: @service.title,
                          currency: 'usd'
  	if @order.save
  	  flash[:success] = "Your Order has been created successfully with charge_id #{charge[:id]}"
      redirect_to user_orders_path
    else
      flash[:danger] = "Couldn't create the order"
      render 'services/show'
    end  
  end

  def user_orders
    @orders = current_user.orders
  end

  private

  def set_service
    @service = Service.find(params[:service_id])
  end

  def order_params
  	params.require(:order).permit(:price, :quantity, :service_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@services = Service.limit(4)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_service, only: [:show, :edit, :update]
  def index
    @services = current_user.services
  end

  def show
    @order = current_user.orders.new
  end

  def new
    @service = current_user.services.build
  end

  def create
    @service = current_user.services.build(service_params)
    if @service.save
      flash[:success] = "Your Service has been created successfully"
      redirect_to @service
    else
      flash[:danger] = "Couldn't create the service"
      redirect_to :back
    end
  end

  def edit
  end

  def update
    # TODO: Save the updated service. Redirect to an appropriate page if save fails.
  end

  private
  def set_service
    @service = Service.find(params[:id])
  end

  def service_params
    params.require(:service).permit(:title, :requirements, :description, :price, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_avatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "https://www.gravatar.com/avatar/#{gravatar_id}.jpg?d=identical&s=150"
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fiverrish</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/navbar' %>
  <div class="zero-pad-mar">
  <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      	<% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/orders/_form.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <%= form_for ([@service, @service.orders.new]) do |f| %>
      <%= f.hidden_field :service_id, value: @service.id %>
      <%= f.hidden_field :price, value: @service.price %>
      <hr>
      <h5 class="pull-left">
        Basic Gig Quantity
      </h5>
      <div class="form-group pull-right">
        <div class="select-control-order-form">
          <%= f.select(:quantity, options_for_select( [
            ["1 (Rs. #{@service.price*1})", 1],
            ["2 (Rs. #{@service.price*2})", 2],
            ["3 (Rs. #{@service.price*3})", 3],
            ["4 (Rs. #{@service.price*4})", 1],
            ["5 (Rs. #{@service.price*5})", 1] ], {id: "quantity"} ) ) %>
        </div>
      </div>
      <br>
      <div class="form-group pull-left">
        <script
          src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key='pk_test_gSycwQHdaT84QXl9iiiFRsph'
          data-name="#{current_user.name}"
        </script>
      </div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
     $("select").bind("change",function() {
       $('.btn-order').html('Order Now - ' + $("select option:selected").html());
     });
 })
</script>

app/views/orders/new.html.erb
<%= render 'form' %>

app/views/orders/user_orders.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <center>
            <%= image_tag get_avatar_url(current_user), class: "img-circle img-responsive img-seller-avatar" %>
            <h3><%= current_user.fullname %></h3>
        </center>
      </div>
      <div class="panel-body">
        <%= current_user.description %>
      </div>
    </div>
  </div>
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
          <h3>My Orders</h3>
      </div>
      <div class="panel-body">
        <% @orders.each do |order| %>
          <div class="row">
            <div class="col-md-2">
              <%= link_to service_path(order.service) do %>
                <%= image_tag order.service.image.url(:thumb) %>
              <% end %>
            </div>
            <div class="col-md-3">
              <%= link_to service_path(order.service) do %>
                <h4><%= order.service.title %></h4>
              <% end %>
            </div>
            <div class="col-md-2">
              <h5>Quantity: <%= order.quantity %> <br/>
              Price: $<%= order.price %></h5>
            </div>
            <div class="col-md-2">
              <h5><%= order.created_at.strftime('%b %d, %Y') %></h5>
            </div>
            <div class="col-md-3">
              <h5>Total Price: $<%= order.total_price %></h5>
            </div>
          </div>
          <hr>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="hero">
  <div class="container">
    <div class="row">
      <div class="hero-heading">
        What do you need done?<br/>
        Find it on Fiverrish.
        <p>Browse. Buy. Done</p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-offset-3 col-md-6">
        <form action="">
          <div class="input-group input-group-lg">
            <input type="text" class="form-control" placeholder="What are you looking for...">
            <span class="input-group-btn">
              <button class="btn btn-default" type="button">
                Find Services
              </button>
            </span>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<div class="container section">
  <h1>
    Newest Gigs
  </h1>
  <div class="row">
    <% @services.each do |service| %>
    <div class="col-md-3">
      <div class="gig-card">
        <%= image_tag service.image, class: "img-responsive", style: "height:275px;" %>
        <h4>
          <%= service.title %>
        </h4>
        <h3>
          <%= "RS. #{service.price}" %>
        </h3>
      </div>
    </div>
    <%end%>
  </div>
</div>

app/views/services/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h2><%= @service.new_record? ? "Create your gig" : "Edit your gig" %></h2>
  </div>
  <div class="panel-body">
    <%= form_for @service do |f| %>
      <% if @service.errors.any? %>
        <div class="alert alert-info">
          <h3>
            Fix the following <%= pluralize(@service.errors.count, "error") %> before continuing:
          </h3>
          <ul>
            <% @service.errors.full_messages.each do |msg| %>
              <li>
                <%= msg %>
              </li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <label>Gig Title</label>
        <%= f.text_area :title, placeholder: "Ex: I will make a logo for you", rows: "2", class: "form-control" %>
      </div>
      <div class="form-group">
        <label>Description</label>
        <%= f.text_area :description, rows: "5", class: "form-control" %>
      </div>
      <div class="form-group">
        <label>Pricing</label>
        <div class="select-control">
          <%= f.select :price, [["Rs. 500", "500"], ["Rs. 1000", "1000"], ["Rs. 1500", "1500"], ["Rs. 2000", "2000"]], placeholder: "Ex: I will make a logo for you", rows: "2", class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <label>Requirements</label>
        <%= f.text_area :requirements, rows: "5", class: "form-control" %>
      </div>
      <div class="form-group">
        <label>Add Photo</label>
        <%= f.file_field :image%>
      </div>
      <hr>
      <%= f.submit @service.new_record? ? "Publish Gig" : "Update Gig", class:"btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/services/create.html.erb
<h1>Services#create</h1>
<p>Find me in app/views/services/create.html.erb</p>

app/views/services/edit.html.erb
<%= render 'form' %>

app/views/services/index.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <center>
          <%= image_tag get_avatar_url(current_user), class: "img-circle img-responsive" %>
          <h3><%= current_user.fullname %></h3>
        </center>
      </div>
      <div class="panel-body">
        <%= current_user.description %>
      </div>
    </div>
  </div>
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>My Gigs</h3>
      </div>
      <div class="panel-body">
        <% @services.each do |service| %>
          <div class="row">
            <div class="col-md-2">
              <%= image_tag service.image.url(:thumb) %>
            </div>
            <div class="col-md-6">
              <h4>
                <%= service.title %>
              </h4>
            </div>
            <div class="col-md-3">
              <%= link_to "Order", service_path(service), class: "btn btn-default pull-right btn-sm"%>
            </div>
            <div class="col-md-1">
              <%= link_to "Update", edit_service_path(service), class: "btn btn-default pull-right btn-sm" %>
            </div>
          </div>
          <hr>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/services/new.html.erb
<%= render 'form' %>

app/views/services/show.html.erb
<br/><br/>
<div class="row">
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>
          <%= @service.title %>
        </h3>
      </div>
      <div class="panel-body">
        <%= image_tag(@service.image.url, :class => 'img-responsive') %>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <%= render 'orders/form' %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>About This Gig</h3>
      </div>
      <div class="panel-body">
        <p><%= @service.description %></p>
      </div>
    </div>
  </div>
</div>

app/views/services/update.html.erb
<h1>Services#update</h1>
<p>Find me in app/views/services/update.html.erb</p>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Fiverrish</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if (user_signed_in?) %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <span><%= image_tag get_avatar_url(current_user), class:"img-circle navbar-avatar"%></span>&nbsp;
              <%= current_user.fullname %>
              <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "View Profile", user_path(current_user.id) %></li>
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li class="dropdown-header">Buying</li>
              <li><%= link_to "My Orders", user_orders_path %></li>
              <li class="dropdown-header">Selling</li>
              <li><%= link_to "My Gigs", services_path %></li>
              <li><%= link_to "Create a Gig", new_service_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Join", new_user_registration_path %></li>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <%= link_to "Start Selling", new_user_session_path, class: "btn btn-navbarcustom" %>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <center>
          <%= image_tag get_avatar_url(@user), class: "img-circle img-responsive" %>
          <h3><%= @user.fullname %></h3>
        </center>
      </div>
      <div class="panel-body">
        <%= @user.description %>
      </div>
    </div>
  </div>
  <div class="col-md-8">
  </div>
</div>